---
type: specs.openrewrite.org/v1beta/recipe
name: org.cortexaidevkit.spring.boot.UpgradeSpringBoot_4_0
displayName: Migrate to Spring Boot 4.0 
recipeList:
  - org.openrewrite.java.spring.boot4.UpgradeSpringBoot_4_0